version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running app.py..."
      - python app.py

artifacts:
  files:
    - '**/*'
  discard-paths: yes
